//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamev2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gamev2.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to † .
        /// </summary>
        internal static string BombSymbol {
            get {
                return ResourceManager.GetString("BombSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◘ .
        /// </summary>
        internal static string CellSymbol {
            get {
                return ResourceManager.GetString("CellSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♀ .
        /// </summary>
        internal static string ExitSymbol {
            get {
                return ResourceManager.GetString("ExitSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - exit.
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♥ .
        /// </summary>
        internal static string LifeSymbol {
            get {
                return ResourceManager.GetString("LifeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom!.
        /// </summary>
        internal static string MessageExplosion {
            get {
                return ResourceManager.GetString("MessageExplosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over!.
        /// </summary>
        internal static string MessageGameOver {
            get {
                return ResourceManager.GetString("MessageGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue? +/-.
        /// </summary>
        internal static string MessageRequestToContinue {
            get {
                return ResourceManager.GetString("MessageRequestToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose!.
        /// </summary>
        internal static string MessageYouLose {
            get {
                return ResourceManager.GetString("MessageYouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win!.
        /// </summary>
        internal static string MessageYouWin {
            get {
                return ResourceManager.GetString("MessageYouWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☺ .
        /// </summary>
        internal static string PersonMarker {
            get {
                return ResourceManager.GetString("PersonMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player has 10 hit points.
        ///10 traps are randomly set on the field, the damage of which is determined randomly (from 1 to 10).
        ///Traps on the field are not visible, the player walks blindly. Does not go beyond the borders.
        ///Good luck.
        ///
        ///.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player has 10 hit points.
        ///10 traps are randomly set on the field, the damage of which is determined randomly (from 1 to 10).
        ///Traps on the field are not visible, the player walks blindly. Does not go beyond the borders.
        ///Good luck.
        ///Warning! God Mode is on. Bomb are visible! You have no damage!
        ///
        ///.
        /// </summary>
        internal static string RulesForGodMode {
            get {
                return ResourceManager.GetString("RulesForGodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your name:.
        /// </summary>
        internal static string SuggestInputUserName {
            get {
                return ResourceManager.GetString("SuggestInputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - you.
        /// </summary>
        internal static string YouTitle {
            get {
                return ResourceManager.GetString("YouTitle", resourceCulture);
            }
        }
    }
}
